id: AC070AA58
title: The Aspiration of the Vajradhātu Maṇḍala
type: translation
pechas:
- ICAAD2993
- I7608C0C8
- ID9F8804F
- I6C8FD8EA
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:32:10.321547
  last_modified_at: 2023-01-04 11:32:10.321558
  collections:
  - Chokgyur Dechen Lingpa
  - Works of Tibetan Masters
alignment_to_base:
  ICAAD2993/53A6: 62CA
  I7608C0C8/F315: 62CA
  ID9F8804F/FFAB: 62CA
  I6C8FD8EA/2CE0: 62CA
